"use client";
import { useState } from "react";
import localFont from "next/font/local";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Login from "./components/Login";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [openLogin, setOpenLogin] = useState(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <Header onLoginClick={() => setOpenLogin(true)} />
        <main className="flex-1 container mx-auto p-4">
          {children}
          {openLogin && <Login onClose={() => setOpenLogin(false)} />}
        </main>
        <Footer />
      </body>
    </html>
  );
}
